### ISSUE TITLE
Emojis break icons

### ISSUE THREAD

**Issue by kbodwin** [mitchelloharawild/icons#25] opened 2019-07-31 20:00 UTC
Hi,

Thanks for the great package!

I've noticed a weird error:  inserting emojis  (direcly or using the `emo` package) seems to cause future icons to break.

See e.g. the attached markdown source and result. 
[icon_reprex.zip](https://github.com/ropenscilabs/icon/files/3453691/icon_reprex.zip)

Any ideas why this is happening?  I can't figure it out!

**Comment by mitchelloharawild** [comment] 2019-08-01 00:07
Hey! Love the reprex :rocket: 
My best guess is that parsing of the icon's asis_output by knitr is not working as intended. This looks like a similar issue to icons in headers (#7).

It appears to work fine with my reimplementation of icon that I've been working on: https://github.com/mitchelloharawild/icon

This rewrite currently only supports fontawesome and HTML output, although it should be much better.
* much smaller file sizes as it uses SVG not fonts (the HTML you've given is 4MB because it contains all fontawesome icons!)
* works in headers (and with emojis seemingly)
* can add icons from any source (`icon_set()`)

**Comment by mitchelloharawild** [comment] 2020-12-13 05:43
Resolved by #31

**Closed as completed by mitchelloharawild** 2020-12-13 05:43 UTC
